version: '2'
services:
    test_jhipster-app:
        image: test_jhipster
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://test_jhipster-mssql:1433;database=test_jhipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    test_jhipster-mssql:
        extends:
            file: mssql.yml
            service: test_jhipster-mssql
